const industriesChipData = [
  "Accounting",
  "Advertising",
  "Aerospace",
  "Agriculture",
  "Airlines/Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel & Fashion",
  "Architecture & Planning",
  "Arts & Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Biotechnology",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies & Equipment",
  "Capital Markets",
  "Chemicals",
  "Civic & Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer & Network Security",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense & Space",
  "Design",
  "E-Learning",
  "Education Management",
  "Electrical & Electronic Manufacturing",
  "Entertainment",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Fishery",
  "Food & Beverages",
  "Food Production",
  "Fundraising",
  "Furniture",
  "Gambling & Casinos",
  "Glass, Ceramics & Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design",
  "Health, Wellness & Fitness",
  "Higher Education",
  "Hospital & Health Care",
  "Hospitality",
  "Human Resources",
  "Import & Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology & Services",
  "Insurance",
  "International Affairs",
  "International Trade & Development",
  "Internet",
  "Investment Banking",
  "Investment Management",
  "Judiciary",
  "Law Enforcement",
  "Law Practice",
  "Legal Services",
  "Legislative Office",
  "Leisure, Travel & Tourism",
  "Libraries",
  "Logistics & Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Market Research",
  "Marketing & Advertising",
  "Mechanical or Industrial Engineering",
  "Media Production",
  "Medical Devices",
  "Medical Practice",
  "Mental Health Care",
  "Military",
  "Mining & Metals",
  "Motion Pictures & Film",
  "Museums & Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers",
  "Nonprofit Organization Management",
  "Oil & Energy",
  "Online Media",
  "Outsourcing/Offshoring",
  "Package/Freight Delivery",
  "Packaging & Containers",
  "Paper & Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary/Secondary Education",
  "Printing",
  "Professional Training & Coaching",
  "Program Development",
  "Public Policy",
  "Public Relations & Communications",
  "Public Safety",
  "Publishing",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Recreational Facilities & Services",
  "Religious Institutions",
  "Renewables & Environment",
  "Research",
  "Restaurants",
  "Retail",
  "Security & Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Staffing & Recruiting",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation & Localization",
  "Transportation/Trucking/Railroad",
  "Utilities",
  "Venture Capital & Private Equity",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine & Spirits",
  "Wireless",
  "Writing & Editing",
  "Space Tech",
  "EdTech",
  "AgriTech",
  "HealthTech",
  "MedTech",
  "FinTech",
  "InsurTech",
  "CleanTech",
  "PropTech",
  "LegalTech",
  "FoodTech",
  "SportsTech",
  "RetailTech",
  "BioTech",
  "DeepTech",
  "Web3",
  "Blockchain",
  "Crypto",
  "NFTs",
  "AI/ML",
  "Robotics",
  "AR/VR",
  "Gaming",
  "eCommerce",
  "Direct-to-Consumer (DTC)",
  "Freelance & Gig Economy",
  "Influencer Marketing",
  "Subscription Services",
  "Digital Media",
  "Podcasting",
  "Smart Home",
  "Home Improvement",
  "Personal Finance",
  "Pet Care",
  "Childcare Services",
  "Elder Care",
  "Mobile Apps",
  "Cybersecurity",
  "DevOps",
  "Cloud Computing",
  "Data Analytics",
  "Big Data",
  "SaaS",
  "PaaS",
  "IaaS",
  "IT Consulting",
  "Game Development",
  "Event Tech",
  "Virtual Events",
  "3D Printing",
  "Smart Wearables",
  "Quantum Computing",
  "Language Learning",
  "Test Prep & Coaching",
  "Tutoring Services",
  "Online Courses",
  "HR Tech",
  "Remote Work Tools",
  "Travel Tech",
  "Hospitality Tech",
  "Energy Storage",
  "Electric Vehicles",
  "Space Tourism",
  "Climate Tech",
  "Sustainable Fashion",
  "Circular Economy",
  "Zero Waste Solutions",
  "Carbon Offsets",
  "Water Purification",
  "Disaster Relief Services",
  "Crowdfunding",
  "Open Source Software",
  "Digital Identity",
  "Smart Contracts",
];

const cityWithCountryChipData = [
  "New York, USA",
  "Los Angeles, USA",
  "London, UK",
  "Paris, France",
  "Berlin, Germany",
  "Tokyo, Japan",
  "Seoul, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Moscow, Russia",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Sydney, Australia",
  "Melbourne, Australia",
  "Rio de Janeiro, Brazil",
  "Buenos Aires, Argentina",
  "Cape Town, South Africa",
  "Cairo, Egypt",
  "Dubai, UAE",
  "Singapore, Singapore",
  "Bangkok, Thailand",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Madrid, Spain",
  "Rome, Italy",
  "Istanbul, Turkey",
  "Amsterdam, Netherlands",
  "Zurich, Switzerland",
  "Stockholm, Sweden",
  "Warsaw, Poland",
  "Dublin, Ireland",
  "Prague, Czech Republic",
  "Vienna, Austria",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Copenhagen, Denmark",
  "Brussels, Belgium",
  "Lisbon, Portugal",
  "Athens, Greece",
  "Budapest, Hungary",
  "Mumbai, India",
  "Delhi, India",
  "Bangalore, India",
  "Hyderabad, India",
  "Ahmedabad, India",
  "Chennai, India",
  "Kolkata, India",
  "Pune, India",
  "Jaipur, India",
  "Surat, India",
  "Lucknow, India",
  "Kanpur, India",
  "Nagpur, India",
  "Indore, India",
  "Thane, India",
  "Bhopal, India",
  "Visakhapatnam, India",
  "Patna, India",
  "Vadodara, India",
  "Ghaziabad, India",
  "Ludhiana, India",
  "Agra, India",
  "Nashik, India",
  "Faridabad, India",
  "Meerut, India",
  "Rajkot, India",
  "Kalyan, India",
  "Vasai-Virar, India",
  "Varanasi, India",
  "Srinagar, India",
  "Aurangabad, India",
  "Dhanbad, India",
  "Amritsar, India",
  "Navi Mumbai, India",
  "Allahabad, India",
  "Ranchi, India",
  "Howrah, India",
  "Coimbatore, India",
  "Jabalpur, India",
  "Gwalior, India",
  "Vijayawada, India",
  "Jodhpur, India",
  "Madurai, India",
  "Raipur, India",
  "Kota, India",
  "Guwahati, India",
  "Chandigarh, India",
  "Solapur, India",
  "Hubli\u2013Dharwad, India",
];

const cityWithoutCountryChipData = [
  "New York",
  "Los Angeles",
  "London",
  "Paris",
  "Berlin",
  "Tokyo",
  "Seoul",
  "Beijing",
  "Shanghai",
  "Moscow",
  "Toronto",
  "Vancouver",
  "Sydney",
  "Melbourne",
  "Rio de Janeiro",
  "Buenos Aires",
  "Cape Town",
  "Cairo",
  "Dubai",
  "Singapore",
  "Bangkok",
  "Kuala Lumpur",
  "Jakarta",
  "Madrid",
  "Rome",
  "Istanbul",
  "Amsterdam",
  "Zurich",
  "Stockholm",
  "Warsaw",
  "Dublin",
  "Prague",
  "Vienna",
  "Oslo",
  "Helsinki",
  "Copenhagen",
  "Brussels",
  "Lisbon",
  "Athens",
  "Budapest",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Ahmedabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Jaipur",
  "Surat",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan",
  "Vasai-Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Ranchi",
  "Howrah",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubli\u2013Dharwad",
];

const rolesLookingForChipData = [
  "Co-founder",
  "Technical Co-founder",
  "Designer",
  "UI/UX Designer",
  "Product Designer",
  "Graphic Designer",
  "Product Manager",
  "Project Manager",
  "Growth Hacker",
  "Marketing Expert",
  "Content Creator",
  "Social Media Manager",
  "Video Editor",
  "Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "React Native Developer",
  "iOS Developer",
  "Android Developer",
  "DevOps Engineer",
  "QA Engineer",
  "Data Scientist",
  "AI/ML Engineer",
  "Blockchain Developer",
  "Web3 Developer",
  "Business Developer",
  "Sales Lead",
  "Finance Expert",
  "Legal Advisor",
  "Operations Lead",
  "HR Manager",
  "Recruiter",
  "Investor",
  "Mentor",
  "Advisor",
  "Beta Tester",
  "Early Adopter",
  "Intern",
  "Volunteer",
  "Consultant",
  "Community Manager",
  "Customer Support",
  "Fundraising Expert",
  "Pitch Coach",
  "Strategic Partner",
  "Startup Enthusiast",
  "Freelancer",
  "Angel Investor",
  "Venture Capitalist",
  "Accelerator/Incubator",
  "No-Code Builder",
  "Low-Code Developer",
  "Technical Writer",
  "Open Source Contributor",
  "Partnership Manager",
  "Product Researcher",
  "Customer Success Manager",
];

const topCompaniesForChipData = [
    "20th Century Studios",
    "ALTBalaji",
    "Accenture",
    "Acer",
    "Adani",
    "Adobe",
    "Airbnb",
    "Airbus",
    "Airtel",
    "Ajio",
    "Alienware",
    "Amazon",
    "Amplitude",
    "Apple",
    "Asana",
    "Ashok Leyland",
    "Asus",
    "Ather Energy",
    "Atlassian",
    "Audi",
    "BCG",
    "BMW",
    "BYD",
    "BYJU\u2019S",
    "Bain & Company",
    "Bajaj",
    "Beats",
    "Belkin",
    "BigBasket",
    "Bitbucket",
    "BluSmart",
    "Blue Origin",
    "Boeing",
    "Bose",
    "Bounce",
    "Branch",
    "Braze",
    "Buffer",
    "Calendly",
    "Canon",
    "Canva",
    "Capgemini",
    "Chime",
    "Cisco",
    "Cleartrip",
    "CleverTap",
    "Cloudflare",
    "Coinbase",
    "Corsair",
    "Coursera",
    "Cred",
    "DC",
    "DJI",
    "Databricks",
    "DeepMind",
    "Dell",
    "Deloitte",
    "DigitalOcean",
    "Disney",
    "DocuSign",
    "DoorDash",
    "Dropbox",
    "Duolingo",
    "EY",
    "EaseMyTrip",
    "Ferrari",
    "Figma",
    "Flipkart",
    "Ford",
    "Freshworks",
    "GE",
    "GitHub",
    "GoPro",
    "Google",
    "Grammarly",
    "Groww",
    "HCLTech",
    "HP",
    "Harman Kardon",
    "Heap",
    "Hero MotoCorp",
    "Hootsuite",
    "Hotstar",
    "Huawei",
    "HubSpot",
    "Hyundai",
    "IBM",
    "IFTTT",
    "Infosys",
    "Instacart",
    "Intel",
    "Intercom",
    "Iterable",
    "JBL",
    "Jio",
    "KPMG",
    "Khan Academy",
    "Kingston",
    "Koo",
    "LG",
    "Lamborghini",
    "Lenovo",
    "LinkedIn",
    "Logitech",
    "Lucid Motors",
    "Lyft",
    "MSI",
    "Mahindra",
    "Mailchimp",
    "Makemytrip",
    "Marshall",
    "Maruti Suzuki",
    "Marvel",
    "McKinsey",
    "Mercedes-Benz",
    "Meta",
    "Microsoft",
    "Mixpanel",
    "MoEngage",
    "Monday.com",
    "Monzo",
    "Myntra",
    "N26",
    "NIO",
    "Netflix",
    "Nikon",
    "Notion",
    "Nvidia",
    "Nykaa",
    "OYO",
    "Okta",
    "Ola Electric",
    "OnePlus",
    "OpenAI",
    "Oppo",
    "Oracle",
    "Palantir",
    "Panasonic",
    "Paramount",
    "Paytm",
    "Phillips",
    "PhonePe",
    "Pinterest",
    "Pixar",
    "Plaid",
    "Policybazaar",
    "Porsche",
    "PwC",
    "Rapido",
    "Razer",
    "Razorpay",
    "Realme",
    "Reddit",
    "Reliance",
    "Revolut",
    "Rivian",
    "Robinhood",
    "Rolls-Royce",
    "Royal Enfield",
    "Salesforce",
    "Samsung",
    "SanDisk",
    "Seagate",
    "Segment",
    "SendGrid",
    "Sennheiser",
    "ServiceNow",
    "Shopify",
    "Siemens",
    "Slack",
    "Snap",
    "Snowflake",
    "Sony",
    "Sony Pictures",
    "SonyLIV",
    "SpaceX",
    "Spotify",
    "Sprinklr",
    "Square",
    "Stripe",
    "Swiggy",
    "TVS Motor",
    "Tata",
    "Tata Consultancy Services",
    "Tech Mahindra",
    "Tesla",
    "TikTok",
    "Trello",
    "Truecaller",
    "Twilio",
    "Twitch",
    "Twitter",
    "Uber",
    "Udemy",
    "Unacademy",
    "Universal Studios",
    "Upstox",
    "Vedantu",
    "Vi",
    "Volkswagen"
  ]

export { topCompaniesForChipData, industriesChipData, cityWithCountryChipData, cityWithoutCountryChipData, rolesLookingForChipData };