const countryData = [
  { code: "AF", name: "Afghanistan", dial_code: "+93", flag: "https://flagcdn.com/w160/af.png" },
  { code: "AX", name: "Aland Islands", dial_code: "++358-18", flag: "https://flagcdn.com/w160/ax.png" },
  { code: "AL", name: "Albania", dial_code: "+355", flag: "https://flagcdn.com/w160/al.png" },
  { code: "DZ", name: "Algeria", dial_code: "+213", flag: "https://flagcdn.com/w160/dz.png" },
  { code: "AS", name: "American Samoa", dial_code: "++1-684", flag: "https://flagcdn.com/w160/as.png" },
  { code: "AD", name: "Andorra", dial_code: "+376", flag: "https://flagcdn.com/w160/ad.png" },
  { code: "AO", name: "Angola", dial_code: "+244", flag: "https://flagcdn.com/w160/ao.png" },
  { code: "AI", name: "Anguilla", dial_code: "++1-264", flag: "https://flagcdn.com/w160/ai.png" },
  { code: "AQ", name: "Antarctica", dial_code: "+672", flag: "https://flagcdn.com/w160/aq.png" },
  { code: "AG", name: "Antigua and Barbuda", dial_code: "++1-268", flag: "https://flagcdn.com/w160/ag.png" },
  { code: "AR", name: "Argentina", dial_code: "+54", flag: "https://flagcdn.com/w160/ar.png" },
  { code: "AM", name: "Armenia", dial_code: "+374", flag: "https://flagcdn.com/w160/am.png" },
  { code: "AW", name: "Aruba", dial_code: "+297", flag: "https://flagcdn.com/w160/aw.png" },
  { code: "AU", name: "Australia", dial_code: "+61", flag: "https://flagcdn.com/w160/au.png" },
  { code: "AT", name: "Austria", dial_code: "+43", flag: "https://flagcdn.com/w160/at.png" },
  { code: "AZ", name: "Azerbaijan", dial_code: "+994", flag: "https://flagcdn.com/w160/az.png" },
  { code: "BS", name: "Bahamas", dial_code: "++1-242", flag: "https://flagcdn.com/w160/bs.png" },
  { code: "BH", name: "Bahrain", dial_code: "+973", flag: "https://flagcdn.com/w160/bh.png" },
  { code: "BD", name: "Bangladesh", dial_code: "+880", flag: "https://flagcdn.com/w160/bd.png" },
  { code: "BB", name: "Barbados", dial_code: "++1-246", flag: "https://flagcdn.com/w160/bb.png" },
  { code: "BY", name: "Belarus", dial_code: "+375", flag: "https://flagcdn.com/w160/by.png" },
  { code: "BE", name: "Belgium", dial_code: "+32", flag: "https://flagcdn.com/w160/be.png" },
  { code: "BZ", name: "Belize", dial_code: "+501", flag: "https://flagcdn.com/w160/bz.png" },
  { code: "BJ", name: "Benin", dial_code: "+229", flag: "https://flagcdn.com/w160/bj.png" },
  { code: "BM", name: "Bermuda", dial_code: "++1-441", flag: "https://flagcdn.com/w160/bm.png" },
  { code: "BT", name: "Bhutan", dial_code: "+975", flag: "https://flagcdn.com/w160/bt.png" },
  { code: "BO", name: "Bolivia", dial_code: "+591", flag: "https://flagcdn.com/w160/bo.png" },
  { code: "BA", name: "Bosnia and Herzegovina", dial_code: "+387", flag: "https://flagcdn.com/w160/ba.png" },
  { code: "BW", name: "Botswana", dial_code: "+267", flag: "https://flagcdn.com/w160/bw.png" },
  { code: "BR", name: "Brazil", dial_code: "+55", flag: "https://flagcdn.com/w160/br.png" },
  { code: "BN", name: "Brunei", dial_code: "+673", flag: "https://flagcdn.com/w160/bn.png" },
  { code: "BG", name: "Bulgaria", dial_code: "+359", flag: "https://flagcdn.com/w160/bg.png" },
  { code: "BF", name: "Burkina Faso", dial_code: "+226", flag: "https://flagcdn.com/w160/bf.png" },
  { code: "BI", name: "Burundi", dial_code: "+257", flag: "https://flagcdn.com/w160/bi.png" },
  { code: "CV", name: "Cape Verde", dial_code: "+238", flag: "https://flagcdn.com/w160/cv.png" },
  { code: "KH", name: "Cambodia", dial_code: "+855", flag: "https://flagcdn.com/w160/kh.png" },
  { code: "CM", name: "Cameroon", dial_code: "+237", flag: "https://flagcdn.com/w160/cm.png" },
  { code: "CA", name: "Canada", dial_code: "+1", flag: "https://flagcdn.com/w160/ca.png" },
  { code: "KY", name: "Cayman Islands", dial_code: "++1-345", flag: "https://flagcdn.com/w160/ky.png" },
  { code: "CF", name: "Central African Republic", dial_code: "+236", flag: "https://flagcdn.com/w160/cf.png" },
  { code: "TD", name: "Chad", dial_code: "+235", flag: "https://flagcdn.com/w160/td.png" },
  { code: "CL", name: "Chile", dial_code: "+56", flag: "https://flagcdn.com/w160/cl.png" },
  { code: "CN", name: "China", dial_code: "+86", flag: "https://flagcdn.com/w160/cn.png" },
  { code: "CX", name: "Christmas Island", dial_code: "+61", flag: "https://flagcdn.com/w160/cx.png" },
  { code: "CC", name: "Cocos Islands", dial_code: "+61", flag: "https://flagcdn.com/w160/cc.png" },
  { code: "CO", name: "Colombia", dial_code: "+57", flag: "https://flagcdn.com/w160/co.png" },
  { code: "KM", name: "Comoros", dial_code: "+269", flag: "https://flagcdn.com/w160/km.png" },
  { code: "CG", name: "Republic of the Congo", dial_code: "+242", flag: "https://flagcdn.com/w160/cg.png" },
  { code: "CD", name: "Democratic Republic of the Congo", dial_code: "+243", flag: "https://flagcdn.com/w160/cd.png" },
  { code: "CK", name: "Cook Islands", dial_code: "+682", flag: "https://flagcdn.com/w160/ck.png" },
  { code: "CR", name: "Costa Rica", dial_code: "+506", flag: "https://flagcdn.com/w160/cr.png" },
  { code: "HR", name: "Croatia", dial_code: "+385", flag: "https://flagcdn.com/w160/hr.png" },
  { code: "CU", name: "Cuba", dial_code: "+53", flag: "https://flagcdn.com/w160/cu.png" },
  { code: "CY", name: "Cyprus", dial_code: "+357", flag: "https://flagcdn.com/w160/cy.png" },
  { code: "CZ", name: "Czech Republic", dial_code: "+420", flag: "https://flagcdn.com/w160/cz.png" },
  { code: "DK", name: "Denmark", dial_code: "+45", flag: "https://flagcdn.com/w160/dk.png" },
  { code: "DJ", name: "Djibouti", dial_code: "+253", flag: "https://flagcdn.com/w160/dj.png" },
  { code: "DM", name: "Dominica", dial_code: "++1-767", flag: "https://flagcdn.com/w160/dm.png" },
  { code: "DO", name: "Dominican Republic", dial_code: "++1-809 and 1-829", flag: "https://flagcdn.com/w160/do.png" },
  { code: "EC", name: "Ecuador", dial_code: "+593", flag: "https://flagcdn.com/w160/ec.png" },
  { code: "EG", name: "Egypt", dial_code: "+20", flag: "https://flagcdn.com/w160/eg.png" },
  { code: "SV", name: "El Salvador", dial_code: "+503", flag: "https://flagcdn.com/w160/sv.png" },
  { code: "GQ", name: "Equatorial Guinea", dial_code: "+240", flag: "https://flagcdn.com/w160/gq.png" },
  { code: "ER", name: "Eritrea", dial_code: "+291", flag: "https://flagcdn.com/w160/er.png" },
  { code: "EE", name: "Estonia", dial_code: "+372", flag: "https://flagcdn.com/w160/ee.png" },
  { code: "ET", name: "Ethiopia", dial_code: "+251", flag: "https://flagcdn.com/w160/et.png" },
  { code: "FK", name: "Falkland Islands", dial_code: "+500", flag: "https://flagcdn.com/w160/fk.png" },
  { code: "FO", name: "Faroe Islands", dial_code: "+298", flag: "https://flagcdn.com/w160/fo.png" },
  { code: "FJ", name: "Fiji", dial_code: "+679", flag: "https://flagcdn.com/w160/fj.png" },
  { code: "FI", name: "Finland", dial_code: "+358", flag: "https://flagcdn.com/w160/fi.png" },
  { code: "FR", name: "France", dial_code: "+33", flag: "https://flagcdn.com/w160/fr.png" },
  { code: "GF", name: "French Guiana", dial_code: "+594", flag: "https://flagcdn.com/w160/gf.png" },
  { code: "PF", name: "French Polynesia", dial_code: "+689", flag: "https://flagcdn.com/w160/pf.png" },
  { code: "TF", name: "French Southern Territories", dial_code: "+262", flag: "https://flagcdn.com/w160/tf.png" },
  { code: "GA", name: "Gabon", dial_code: "+241", flag: "https://flagcdn.com/w160/ga.png" },
  { code: "GM", name: "Gambia", dial_code: "+220", flag: "https://flagcdn.com/w160/gm.png" },
  { code: "GE", name: "Georgia", dial_code: "+995", flag: "https://flagcdn.com/w160/ge.png" },
  { code: "DE", name: "Germany", dial_code: "+49", flag: "https://flagcdn.com/w160/de.png" },
  { code: "GH", name: "Ghana", dial_code: "+233", flag: "https://flagcdn.com/w160/gh.png" },
  { code: "GI", name: "Gibraltar", dial_code: "+350", flag: "https://flagcdn.com/w160/gi.png" },
  { code: "GR", name: "Greece", dial_code: "+30", flag: "https://flagcdn.com/w160/gr.png" },
  { code: "GL", name: "Greenland", dial_code: "+299", flag: "https://flagcdn.com/w160/gl.png" },
  { code: "GD", name: "Grenada", dial_code: "++1-473", flag: "https://flagcdn.com/w160/gd.png" },
  { code: "GP", name: "Guadeloupe", dial_code: "+590", flag: "https://flagcdn.com/w160/gp.png" },
  { code: "GU", name: "Guam", dial_code: "++1-671", flag: "https://flagcdn.com/w160/gu.png" },
  { code: "GT", name: "Guatemala", dial_code: "+502", flag: "https://flagcdn.com/w160/gt.png" },
  { code: "GN", name: "Guinea", dial_code: "+224", flag: "https://flagcdn.com/w160/gn.png" },
  { code: "GW", name: "Guinea-Bissau", dial_code: "+245", flag: "https://flagcdn.com/w160/gw.png" },
  { code: "GY", name: "Guyana", dial_code: "+592", flag: "https://flagcdn.com/w160/gy.png" },
  { code: "HT", name: "Haiti", dial_code: "+509", flag: "https://flagcdn.com/w160/ht.png" },
  { code: "HM", name: "Heard Island and McDonald Islands", dial_code: "+ ", flag: "https://flagcdn.com/w160/hm.png" },
  { code: "VA", name: "Vatican", dial_code: "+379", flag: "https://flagcdn.com/w160/va.png" },
  { code: "HN", name: "Honduras", dial_code: "+504", flag: "https://flagcdn.com/w160/hn.png" },
  { code: "HK", name: "Hong Kong", dial_code: "+852", flag: "https://flagcdn.com/w160/hk.png" },
  { code: "HU", name: "Hungary", dial_code: "+36", flag: "https://flagcdn.com/w160/hu.png" },
  { code: "IS", name: "Iceland", dial_code: "+354", flag: "https://flagcdn.com/w160/is.png" },
  { code: "IN", name: "India", dial_code: "+91", flag: "https://flagcdn.com/w160/in.png" },
  { code: "ID", name: "Indonesia", dial_code: "+62", flag: "https://flagcdn.com/w160/id.png" },
  { code: "IR", name: "Iran", dial_code: "+98", flag: "https://flagcdn.com/w160/ir.png" },
  { code: "IQ", name: "Iraq", dial_code: "+964", flag: "https://flagcdn.com/w160/iq.png" },
  { code: "IE", name: "Ireland", dial_code: "+353", flag: "https://flagcdn.com/w160/ie.png" },
  { code: "IM", name: "Isle of Man", dial_code: "++44-1624", flag: "https://flagcdn.com/w160/im.png" },
  { code: "IL", name: "Israel", dial_code: "+972", flag: "https://flagcdn.com/w160/il.png" },
  { code: "IT", name: "Italy", dial_code: "+39", flag: "https://flagcdn.com/w160/it.png" },
  { code: "CI", name: "Ivory Coast", dial_code: "+225", flag: "https://flagcdn.com/w160/ci.png" },
  { code: "JM", name: "Jamaica", dial_code: "++1-876", flag: "https://flagcdn.com/w160/jm.png" },
  { code: "JP", name: "Japan", dial_code: "+81", flag: "https://flagcdn.com/w160/jp.png" },
  { code: "JE", name: "Jersey", dial_code: "++44-1534", flag: "https://flagcdn.com/w160/je.png" },
  { code: "JO", name: "Jordan", dial_code: "+962", flag: "https://flagcdn.com/w160/jo.png" },
  { code: "KZ", name: "Kazakhstan", dial_code: "+7", flag: "https://flagcdn.com/w160/kz.png" },
  { code: "KE", name: "Kenya", dial_code: "+254", flag: "https://flagcdn.com/w160/ke.png" },
  { code: "KI", name: "Kiribati", dial_code: "+686", flag: "https://flagcdn.com/w160/ki.png" },
  { code: "KP", name: "North Korea", dial_code: "+850", flag: "https://flagcdn.com/w160/kp.png" },
  { code: "KR", name: "South Korea", dial_code: "+82", flag: "https://flagcdn.com/w160/kr.png" },
  { code: "KW", name: "Kuwait", dial_code: "+965", flag: "https://flagcdn.com/w160/kw.png" },
  { code: "KG", name: "Kyrgyzstan", dial_code: "+996", flag: "https://flagcdn.com/w160/kg.png" },
  { code: "LA", name: "Laos", dial_code: "+856", flag: "https://flagcdn.com/w160/la.png" },
  { code: "LV", name: "Latvia", dial_code: "+371", flag: "https://flagcdn.com/w160/lv.png" },
  { code: "LB", name: "Lebanon", dial_code: "+961", flag: "https://flagcdn.com/w160/lb.png" },
  { code: "LS", name: "Lesotho", dial_code: "+266", flag: "https://flagcdn.com/w160/ls.png" },
  { code: "LR", name: "Liberia", dial_code: "+231", flag: "https://flagcdn.com/w160/lr.png" },
  { code: "LY", name: "Libya", dial_code: "+218", flag: "https://flagcdn.com/w160/ly.png" },
  { code: "LI", name: "Liechtenstein", dial_code: "+423", flag: "https://flagcdn.com/w160/li.png" },
  { code: "LT", name: "Lithuania", dial_code: "+370", flag: "https://flagcdn.com/w160/lt.png" },
  { code: "LU", name: "Luxembourg", dial_code: "+352", flag: "https://flagcdn.com/w160/lu.png" },
  { code: "MO", name: "Macao", dial_code: "+853", flag: "https://flagcdn.com/w160/mo.png" },
  { code: "MK", name: "Macedonia", dial_code: "+389", flag: "https://flagcdn.com/w160/mk.png" },
  { code: "MG", name: "Madagascar", dial_code: "+261", flag: "https://flagcdn.com/w160/mg.png" },
  { code: "MW", name: "Malawi", dial_code: "+265", flag: "https://flagcdn.com/w160/mw.png" },
  { code: "MY", name: "Malaysia", dial_code: "+60", flag: "https://flagcdn.com/w160/my.png" },
  { code: "MV", name: "Maldives", dial_code: "+960", flag: "https://flagcdn.com/w160/mv.png" },
  { code: "ML", name: "Mali", dial_code: "+223", flag: "https://flagcdn.com/w160/ml.png" },
  { code: "MT", name: "Malta", dial_code: "+356", flag: "https://flagcdn.com/w160/mt.png" },
  { code: "MH", name: "Marshall Islands", dial_code: "+692", flag: "https://flagcdn.com/w160/mh.png" },
  { code: "MQ", name: "Martinique", dial_code: "+596", flag: "https://flagcdn.com/w160/mq.png" },
  { code: "MR", name: "Mauritania", dial_code: "+222", flag: "https://flagcdn.com/w160/mr.png" },
  { code: "MU", name: "Mauritius", dial_code: "+230", flag: "https://flagcdn.com/w160/mu.png" },
  { code: "YT", name: "Mayotte", dial_code: "+262", flag: "https://flagcdn.com/w160/yt.png" },
  { code: "MX", name: "Mexico", dial_code: "+52", flag: "https://flagcdn.com/w160/mx.png" },
  { code: "FM", name: "Micronesia", dial_code: "+691", flag: "https://flagcdn.com/w160/fm.png" },
  { code: "MD", name: "Moldova", dial_code: "+373", flag: "https://flagcdn.com/w160/md.png" },
  { code: "MC", name: "Monaco", dial_code: "+377", flag: "https://flagcdn.com/w160/mc.png" },  
  { code: "MN", name: "Mongolia", dial_code: "+976", flag: "https://flagcdn.com/w160/mn.png" },
  { code: "ME", name: "Montenegro", dial_code: "+382", flag: "https://flagcdn.com/w160/me.png" },
  { code: "MS", name: "Montserrat", dial_code: "++1-664", flag: "https://flagcdn.com/w160/ms.png" },
  { code: "MA", name: "Morocco", dial_code: "+212", flag: "https://flagcdn.com/w160/ma.png" },
  { code: "MZ", name: "Mozambique", dial_code: "+258", flag: "https://flagcdn.com/w160/mz.png" },
  { code: "MM", name: "Myanmar", dial_code: "+95", flag: "https://flagcdn.com/w160/mm.png" },
  { code: "NA", name: "Namibia", dial_code: "+264", flag: "https://flagcdn.com/w160/na.png" },
  { code: "NR", name: "Nauru", dial_code: "+674", flag: "https://flagcdn.com/w160/nr.png" },
  { code: "NP", name: "Nepal", dial_code: "+977", flag: "https://flagcdn.com/w160/np.png" },
  { code: "NL", name: "Netherlands", dial_code: "+31", flag: "https://flagcdn.com/w160/nl.png" },
  { code: "NC", name: "New Caledonia", dial_code: "+687", flag: "https://flagcdn.com/w160/nc.png" },
  { code: "NZ", name: "New Zealand", dial_code: "+64", flag: "https://flagcdn.com/w160/nz.png" },
  { code: "NI", name: "Nicaragua", dial_code: "+505", flag: "https://flagcdn.com/w160/ni.png" },
  { code: "NE", name: "Niger", dial_code: "+227", flag: "https://flagcdn.com/w160/ne.png" },
  { code: "NG", name: "Nigeria", dial_code: "+234", flag: "https://flagcdn.com/w160/ng.png" },
  { code: "NU", name: "Niue", dial_code: "+683", flag: "https://flagcdn.com/w160/nu.png" },
  { code: "MP", name: "Northern Mariana Islands", dial_code: "++1-670", flag: "https://flagcdn.com/w160/mp.png" },
  { code: "NO", name: "Norway", dial_code: "+47", flag: "https://flagcdn.com/w160/no.png" },
  { code: "OM", name: "Oman", dial_code: "+968", flag: "https://flagcdn.com/w160/om.png" },
  { code: "PK", name: "Pakistan", dial_code: "+92", flag: "https://flagcdn.com/w160/pk.png" },
  { code: "PW", name: "Palau", dial_code: "+680", flag: "https://flagcdn.com/w160/pw.png" },
  { code: "PS", name: "Palestinian Territory", dial_code: "+970", flag: "https://flagcdn.com/w160/ps.png" },
  { code: "PA", name: "Panama", dial_code: "+507", flag: "https://flagcdn.com/w160/pa.png" },
  { code: "PG", name: "Papua New Guinea", dial_code: "+675", flag: "https://flagcdn.com/w160/pg.png" },
  { code: "PY", name: "Paraguay", dial_code: "+595", flag: "https://flagcdn.com/w160/py.png" },
  { code: "PE", name: "Peru", dial_code: "+51", flag: "https://flagcdn.com/w160/pe.png" },
  { code: "PH", name: "Philippines", dial_code: "+63", flag: "https://flagcdn.com/w160/ph.png" },
  { code: "PL", name: "Poland", dial_code: "+48", flag: "https://flagcdn.com/w160/pl.png" },
  { code: "PT", name: "Portugal", dial_code: "+351", flag: "https://flagcdn.com/w160/pt.png" },
  { code: "PR", name: "Puerto Rico", dial_code: "++1-787 and 1-939", flag: "https://flagcdn.com/w160/pr.png" },
  { code: "RO", name: "Romania", dial_code: "+40", flag: "https://flagcdn.com/w160/ro.png" },
  { code: "RU", name: "Russia", dial_code: "+7", flag: "https://flagcdn.com/w160/ru.png" },
  { code: "RW", name: "Rwanda", dial_code: "+250", flag: "https://flagcdn.com/w160/rw.png" },
  { code: "KN", name: "Saint Kitts and Nevis", dial_code: "++1-869", flag: "https://flagcdn.com/w160/kn.png" },
  { code: "LC", name: "Saint Lucia", dial_code: "++1-758", flag: "https://flagcdn.com/w160/lc.png" },
  { code: "MF", name: "Saint Martin", dial_code: "+590", flag: "https://flagcdn.com/w160/mf.png" },
  { code: "PM", name: "Saint Pierre and Miquelon", dial_code: "+508", flag: "https://flagcdn.com/w160/pm.png" },
  { code: "VC", name: "Saint Vincent and the Grenadines", dial_code: "++1-784", flag: "https://flagcdn.com/w160/vc.png" },
  { code: "WS", name: "Samoa", dial_code: "+685", flag: "https://flagcdn.com/w160/ws.png" },
  { code: "SM", name: "San Marino", dial_code: "+378", flag: "https://flagcdn.com/w160/sm.png" },
  { code: "ST", name: "Sao Tome and Principe", dial_code: "+239", flag: "https://flagcdn.com/w160/st.png" },
  { code: "SA", name: "Saudi Arabia", dial_code: "+966", flag: "https://flagcdn.com/w160/sa.png" },
  { code: "SN", name: "Senegal", dial_code: "+221", flag: "https://flagcdn.com/w160/sn.png" },
  { code: "RS", name: "Serbia", dial_code: "+381", flag: "https://flagcdn.com/w160/rs.png" },
  { code: "SC", name: "Seychelles", dial_code: "+248", flag: "https://flagcdn.com/w160/sc.png" },
  { code: "SL", name: "Sierra Leone", dial_code: "+232", flag: "https://flagcdn.com/w160/sl.png" },
  { code: "SG", name: "Singapore", dial_code: "+65", flag: "https://flagcdn.com/w160/sg.png" },
  { code: "SK", name: "Slovakia", dial_code: "+421", flag: "https://flagcdn.com/w160/sk.png" },
  { code: "SI", name: "Slovenia", dial_code: "+386", flag: "https://flagcdn.com/w160/si.png" },
  { code: "SB", name: "Solomon Islands", dial_code: "+677", flag: "https://flagcdn.com/w160/sb.png" },
  { code: "SO", name: "Somalia", dial_code: "+252", flag: "https://flagcdn.com/w160/so.png" },
  { code: "ZA", name: "South Africa", dial_code: "+27", flag: "https://flagcdn.com/w160/za.png" },
  { code: "ES", name: "Spain", dial_code: "+34", flag: "https://flagcdn.com/w160/es.png" },
  { code: "LK", name: "Sri Lanka", dial_code: "+94", flag: "https://flagcdn.com/w160/lk.png" },
  { code: "SD", name: "Sudan", dial_code: "+249", flag: "https://flagcdn.com/w160/sd.png" },
  { code: "SR", name: "Suriname", dial_code: "+597", flag: "https://flagcdn.com/w160/sr.png" },
  { code: "SZ", name: "Swaziland", dial_code: "+268", flag: "https://flagcdn.com/w160/sz.png" },
  { code: "SE", name: "Sweden", dial_code: "+46", flag: "https://flagcdn.com/w160/se.png" },
  { code: "CH", name: "Switzerland", dial_code: "+41", flag: "https://flagcdn.com/w160/ch.png" },
  { code: "SY", name: "Syria", dial_code: "+963", flag: "https://flagcdn.com/w160/sy.png" },
  { code: "TW", name: "Taiwan", dial_code: "+886", flag: "https://flagcdn.com/w160/tw.png" },
  { code: "TJ", name: "Tajikistan", dial_code: "+992", flag: "https://flagcdn.com/w160/tj.png" },
  { code: "TZ", name: "Tanzania", dial_code: "+255", flag: "https://flagcdn.com/w160/tz.png" },
  { code: "TH", name: "Thailand", dial_code: "+66", flag: "https://flagcdn.com/w160/th.png" },
  { code: "TG", name: "Togo", dial_code: "+228", flag: "https://flagcdn.com/w160/tg.png" },
  { code: "TK", name: "Tokelau", dial_code: "+690", flag: "https://flagcdn.com/w160/tk.png" },
  { code: "TO", name: "Tonga", dial_code: "+676", flag: "https://flagcdn.com/w160/to.png" },
  { code: "TT", name: "Trinidad and Tobago", dial_code: "++1-868", flag: "https://flagcdn.com/w160/tt.png" },
  { code: "TN", name: "Tunisia", dial_code: "+216", flag: "https://flagcdn.com/w160/tn.png" },
  { code: "TR", name: "Turkey", dial_code: "+90", flag: "https://flagcdn.com/w160/tr.png" },
  { code: "TM", name: "Turkmenistan", dial_code: "+993", flag: "https://flagcdn.com/w160/tm.png" },
  { code: "TC", name: "Turks and Caicos Islands", dial_code: "++1-649", flag: "https://flagcdn.com/w160/tc.png" },
  { code: "TV", name: "Tuvalu", dial_code: "+688", flag: "https://flagcdn.com/w160/tv.png" },
  { code: "UG", name: "Uganda", dial_code: "+256", flag: "https://flagcdn.com/w160/ug.png" },
  { code: "UA", name: "Ukraine", dial_code: "+380", flag: "https://flagcdn.com/w160/ua.png" },
  { code: "AE", name: "United Arab Emirates", dial_code: "+971", flag: "https://flagcdn.com/w160/ae.png" },
  { code: "GB", name: "United Kingdom", dial_code: "+44", flag: "https://flagcdn.com/w160/gb.png" },
  { code: "US", name: "United States", dial_code: "+1", flag: "https://flagcdn.com/w160/us.png" },
  { code: "UY", name: "Uruguay", dial_code: "+598", flag: "https://flagcdn.com/w160/uy.png" },
  { code: "UZ", name: "Uzbekistan", dial_code: "+998", flag: "https://flagcdn.com/w160/uz.png" },
  { code: "VU", name: "Vanuatu", dial_code: "+678", flag: "https://flagcdn.com/w160/vu.png" },
  { code: "VA", name: "Vatican", dial_code: "+379", flag: "https://flagcdn.com/w160/va.png" },
  { code: "VE", name: "Venezuela", dial_code: "+58", flag: "https://flagcdn.com/w160/ve.png" },
  { code: "VN", name: "Vietnam", dial_code: "+84", flag: "https://flagcdn.com/w160/vn.png" },
  { code: "VG", name: "British Virgin Islands", dial_code: "++1-284", flag: "https://flagcdn.com/w160/vg.png" },
  { code: "VI", name: "U.S. Virgin Islands", dial_code: "++1-340", flag: "https://flagcdn.com/w160/vi.png" },
  { code: "WF", name: "Wallis and Futuna", dial_code: "+681", flag: "https://flagcdn.com/w160/wf.png" },
  { code: "EH", name: "Western Sahara", dial_code: "+212", flag: "https://flagcdn.com/w160/eh.png" },
  { code: "YE", name: "Yemen", dial_code: "+967", flag: "https://flagcdn.com/w160/ye.png" },
  { code: "ZM", name: "Zambia", dial_code: "+260", flag: "https://flagcdn.com/w160/zm.png" },
  { code: "ZW", name: "Zimbabwe", dial_code: "+263", flag: "https://flagcdn.com/w160/zw.png" },
];

export default countryData;
